apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bd-pvc
  namespace: atorres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "bd-pv"