apiVersion: v1
kind: PersistentVolume
metadata:
  name: bd-pv
  namespace: atorres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: bd-pvc
    namespace: atorres